import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function POST(req: Request) {
  try {
    const { prompt } = await req.json();

    const pdfDoc = await PDFDocument.create();

    // ✅ Safe built-in fonts only
    const titleFont = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);
    const bodyFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);

    const page = pdfDoc.addPage([595, 842]); // A4
    const { width, height } = page.getSize();

    const margin = 50;
    let cursorY = height - 80;

    /* ---------------- Title ---------------- */
    const titleText = "ARKEES AI – Generated PDF";
    page.drawText(titleText, {
      x: margin,
      y: cursorY,
      size: 22,
      font: titleFont,
      color: rgb(0.1, 0.1, 0.1),
    });

    cursorY -= 40;

    /* ---------------- Body ---------------- */
    const bodyText = prompt || "ARKEES AI PDF Engine";
    const fontSize = 14;
    const lineHeight = fontSize + 6;
    const maxWidth = width - margin * 2;

    const words = bodyText.split(" ");
    let line = "";

    for (const word of words) {
      const testLine = line + word + " ";
      const textWidth = bodyFont.widthOfTextAtSize(testLine, fontSize);

      if (textWidth > maxWidth) {
        page.drawText(line, {
          x: margin,
          y: cursorY,
          size: fontSize,
          font: bodyFont,
          color: rgb(0, 0, 0),
        });
        line = word + " ";
        cursorY -= lineHeight;
      } else {
        line = testLine;
      }
    }

    // draw remaining line
    if (line) {
      page.drawText(line, {
        x: margin,
        y: cursorY,
        size: fontSize,
        font: bodyFont,
        color: rgb(0, 0, 0),
      });
    }

    /* ---------------- Footer ---------------- */
    page.drawLine({
      start: { x: margin, y: 60 },
      end: { x: width - margin, y: 60 },
      thickness: 1,
      color: rgb(0.8, 0.8, 0.8),
    });

    page.drawText("Generated by ARKEES AI • Think Less. Create More.", {
      x: margin,
      y: 40,
      size: 10,
      font: bodyFont,
      color: rgb(0.4, 0.4, 0.4),
    });

    const pdfBytes = await pdfDoc.save();

    return new Response(pdfBytes, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=arkees-ai.pdf",
      },
    });
  } catch (err) {
    console.error("PDF ERROR:", err);
    return NextResponse.json(
      { error: "PDF generation failed" },
      { status: 500 }
    );
  }
}
